require('dotenv').config();
const mongoose = require('mongoose');
const Product = require('../models/Product');
const connectDB = require('../config/db');

// Import product data from existing frontend files
// Note: These are the hardcoded arrays from the frontend
const mensProducts = [
  {
    id: 1,
    title: "Men's Black Shirt",
    brand: "MONTREZ",
    price: 799,
    mrp: 1999,
    discount: "75% OFF",
    rating: "4.2",
    ratingCount: "12,352",
    images: ["product_images/item1.png", "product_images/item1.1.png", "product_images/item1.2.png", "product_images/item1.3.png"],
    colors: ["product_images/item1.png", "product_images/item1.1.png", "product_images/item1.2.png"],
    category: "mens",
    description: "Premium quality men's black shirt made from high-quality fabric",
  },
  {
    id: 2,
    title: "Men Solid Round Neck Pure Cotton Dark Green T-Shirt",
    brand: "WIERDO",
    price: 379,
    mrp: 1099,
    discount: "65% OFF",
    rating: "4.3",
    ratingCount: "600",
    images: ["product_images/item2.png", "product_images/item2.1.png", "product_images/item2.2.png", "product_images/item2.3.png"],
    colors: ["product_images/item2.1.png", "product_images/item2.2.png"],
    category: "mens",
    description: "Comfortable men's round neck t-shirt in dark green color",
  },
  {
    id: 3,
    title: "Men Slim Fit Solid Mandarin Collar Casual Shirt",
    brand: "FUBAR",
    price: 255,
    mrp: 1200,
    discount: "76% OFF",
    rating: "4.5",
    ratingCount: "5000",
    images: ["product_images/item3.png", "product_images/item3.1.png"],
    colors: ["product_images/item3.png"],
    category: "mens",
    description: "Stylish men's slim fit casual shirt with mandarin collar",
  },
  {
    id: 4,
    title: "Men's Cotton Casual Shirt",
    brand: "LOUIS PHILIPPE",
    price: 599,
    mrp: 1499,
    discount: "60% OFF",
    rating: "4.4",
    ratingCount: "8000",
    images: ["product_images/item4.png"],
    colors: ["product_images/item4.png"],
    category: "mens",
    description: "Premium cotton casual shirt for men",
  },
  {
    id: 5,
    title: "Men's Formal Shirt",
    brand: "PETER ENGLAND",
    price: 699,
    mrp: 1799,
    discount: "61% OFF",
    rating: "4.6",
    ratingCount: "6000",
    images: ["product_images/item5.png"],
    colors: ["product_images/item5.png"],
    category: "mens",
    description: "Elegant men's formal shirt for office and special occasions",
  },
  {
    id: 6,
    title: "Men's Hoodie",
    brand: "NIKE",
    price: 1299,
    mrp: 2999,
    discount: "57% OFF",
    rating: "4.5",
    ratingCount: "3000",
    images: ["product_images/item6.png"],
    colors: ["product_images/item6.png"],
    category: "mens",
    description: "Comfortable men's hoodie perfect for cold weather",
  },
  {
    id: 7,
    title: "Men's Sweatshirt",
    brand: "ADIDAS",
    price: 999,
    mrp: 2299,
    discount: "57% OFF",
    rating: "4.4",
    ratingCount: "4000",
    images: ["product_images/item7.png"],
    colors: ["product_images/item7.png"],
    category: "mens",
    description: "Stylish men's sweatshirt for casual wear",
  },
  {
    id: 8,
    title: "Men's Polo Shirt",
    brand: "TOMMY HILFIGER",
    price: 849,
    mrp: 1999,
    discount: "58% OFF",
    rating: "4.3",
    ratingCount: "2000",
    images: ["product_images/item8.png"],
    colors: ["product_images/item8.png"],
    category: "mens",
    description: "Classic men's polo shirt in multiple colors",
  },
  {
    id: 9,
    title: "Men's Denim Shirt",
    brand: "LEVIS",
    price: 1199,
    mrp: 2499,
    discount: "52% OFF",
    rating: "4.5",
    ratingCount: "5500",
    images: ["product_images/item9.png"],
    colors: ["product_images/item9.png"],
    category: "mens",
    description: "Rugged men's denim shirt for versatile styling",
  },
  {
    id: 10,
    title: "Men's Henley Shirt",
    brand: "BASIC ESSENTIALS",
    price: 299,
    mrp: 899,
    discount: "67% OFF",
    rating: "4.2",
    ratingCount: "1500",
    images: ["product_images/item10.png"],
    colors: ["product_images/item10.png"],
    category: "mens",
    description: "Simple yet stylish men's henley shirt",
  },
  {
    id: 11,
    title: "Men's Cargo Shirt",
    brand: "ARMY",
    price: 699,
    mrp: 1699,
    discount: "59% OFF",
    rating: "4.3",
    ratingCount: "3000",
    images: ["product_images/item11.png"],
    colors: ["product_images/item11.png"],
    category: "mens",
    description: "Practical men's cargo shirt with multiple pockets",
  },
  {
    id: 12,
    title: "Men's Oxford Shirt",
    brand: "RAYMOND",
    price: 999,
    mrp: 2299,
    discount: "57% OFF",
    rating: "4.6",
    ratingCount: "4500",
    images: ["product_images/item12.png"],
    colors: ["product_images/item12.png"],
    category: "mens",
    description: "Premium oxford cloth shirt for men",
  },
];

const womensProducts = [
  {
    id: 13,
    title: "Women's Kurta",
    brand: "BIBA",
    price: 499,
    mrp: 1299,
    discount: "62% OFF",
    rating: "4.4",
    ratingCount: "5000",
    images: ["product_images/women_item1.png"],
    colors: ["product_images/women_item1.png"],
    category: "womens",
    description: "Traditional women's kurta in vibrant colors",
  },
  {
    id: 14,
    title: "Women's Saree",
    brand: "SAREE HEAVEN",
    price: 899,
    mrp: 2499,
    discount: "64% OFF",
    rating: "4.5",
    ratingCount: "3000",
    images: ["product_images/women_item2.png"],
    colors: ["product_images/women_item2.png"],
    category: "womens",
    description: "Elegant women's saree perfect for festivals",
  },
  {
    id: 15,
    title: "Women's Lehenga",
    brand: "ETHNIC WEAR",
    price: 1299,
    mrp: 3499,
    discount: "63% OFF",
    rating: "4.6",
    ratingCount: "2500",
    images: ["product_images/women_item3.png"],
    colors: ["product_images/women_item3.png"],
    category: "womens",
    description: "Beautiful women's lehenga for special occasions",
  },
  {
    id: 16,
    title: "Women's Anarkali Suit",
    brand: "SALWAR HOUSE",
    price: 599,
    mrp: 1599,
    discount: "63% OFF",
    rating: "4.4",
    ratingCount: "2000",
    images: ["product_images/women_item4.png"],
    colors: ["product_images/women_item4.png"],
    category: "womens",
    description: "Stylish women's anarkali suit",
  },
  {
    id: 17,
    title: "Women's Salwar Kameez",
    brand: "COTTON WEAR",
    price: 399,
    mrp: 1099,
    discount: "64% OFF",
    rating: "4.3",
    ratingCount: "3500",
    images: ["product_images/women_item5.png"],
    colors: ["product_images/women_item5.png"],
    category: "womens",
    description: "Comfortable women's cotton salwar kameez",
  },
  {
    id: 18,
    title: "Women's Palazzo Suit",
    brand: "WESTERN WEAR",
    price: 599,
    mrp: 1499,
    discount: "60% OFF",
    rating: "4.4",
    ratingCount: "2000",
    images: ["product_images/women_item6.png"],
    colors: ["product_images/women_item6.png"],
    category: "womens",
    description: "Contemporary women's palazzo suit",
  },
  {
    id: 19,
    title: "Women's Crop Top",
    brand: "URBAN WEAR",
    price: 299,
    mrp: 899,
    discount: "67% OFF",
    rating: "4.2",
    ratingCount: "1500",
    images: ["product_images/women_item7.png"],
    colors: ["product_images/women_item7.png"],
    category: "womens",
    description: "Trendy women's crop top",
  },
  {
    id: 20,
    title: "Women's Jeans",
    brand: "LEVIS",
    price: 799,
    mrp: 1999,
    discount: "60% OFF",
    rating: "4.5",
    ratingCount: "4000",
    images: ["product_images/women_item8.png"],
    colors: ["product_images/women_item8.png"],
    category: "womens",
    description: "Classic women's denim jeans",
  },
  {
    id: 21,
    title: "Women's Dress",
    brand: "FOREVER 21",
    price: 599,
    mrp: 1599,
    discount: "63% OFF",
    rating: "4.4",
    ratingCount: "2500",
    images: ["product_images/women_item9.png"],
    colors: ["product_images/women_item9.png"],
    category: "womens",
    description: "Casual and elegant women's dress",
  },
  {
    id: 22,
    title: "Women's Sweater",
    brand: "MARKS & SPENCER",
    price: 799,
    mrp: 1999,
    discount: "60% OFF",
    rating: "4.3",
    ratingCount: "1800",
    images: ["product_images/women_item10.png"],
    colors: ["product_images/women_item10.png"],
    category: "womens",
    description: "Warm women's sweater for winter",
  },
  {
    id: 23,
    title: "Women's Jacket",
    brand: "TOMMY HILFIGER",
    price: 1299,
    mrp: 3299,
    discount: "61% OFF",
    rating: "4.6",
    ratingCount: "2000",
    images: ["product_images/women_item11.png"],
    colors: ["product_images/women_item11.png"],
    category: "womens",
    description: "Premium women's casual jacket",
  },
  {
    id: 24,
    title: "Women's Blazer",
    brand: "FORMAL WEAR",
    price: 999,
    mrp: 2499,
    discount: "60% OFF",
    rating: "4.5",
    ratingCount: "2500",
    images: ["product_images/women_item12.png"],
    colors: ["product_images/women_item12.png"],
    category: "womens",
    description: "Elegant women's formal blazer",
  },
];

const kidsProducts = [
  {
    id: 25,
    title: "Kids' T-Shirt",
    brand: "KIDS WORLD",
    price: 199,
    mrp: 599,
    discount: "67% OFF",
    rating: "4.2",
    ratingCount: "1000",
    images: ["product_images/kids_item1.png"],
    colors: ["product_images/kids_item1.png"],
    category: "kids",
    description: "Comfortable kids' t-shirt in various colors",
  },
  {
    id: 26,
    title: "Kids' Shorts",
    brand: "LITTLE ONES",
    price: 249,
    mrp: 699,
    discount: "64% OFF",
    rating: "4.3",
    ratingCount: "800",
    images: ["product_images/kids_item2.png"],
    colors: ["product_images/kids_item2.png"],
    category: "kids",
    description: "Cute kids' shorts perfect for summer",
  },
  {
    id: 27,
    title: "Kids' Track Pants",
    brand: "COMFORT KIDS",
    price: 299,
    mrp: 799,
    discount: "63% OFF",
    rating: "4.4",
    ratingCount: "1200",
    images: ["product_images/kids_item3.png"],
    colors: ["product_images/kids_item3.png"],
    category: "kids",
    description: "Comfortable kids' track pants",
  },
  {
    id: 28,
    title: "Kids' Dress",
    brand: "PRINCESS WEAR",
    price: 399,
    mrp: 1099,
    discount: "64% OFF",
    rating: "4.5",
    ratingCount: "1500",
    images: ["product_images/kids_item4.png"],
    colors: ["product_images/kids_item4.png"],
    category: "kids",
    description: "Beautiful kids' dress for festivals",
  },
  {
    id: 29,
    title: "Kids' Hoodie",
    brand: "COZY KIDS",
    price: 499,
    mrp: 1299,
    discount: "62% OFF",
    rating: "4.3",
    ratingCount: "900",
    images: ["product_images/kids_item5.png"],
    colors: ["product_images/kids_item5.png"],
    category: "kids",
    description: "Warm kids' hoodie for cold weather",
  },
  {
    id: 30,
    title: "Kids' Jeans",
    brand: "DENIM KIDS",
    price: 349,
    mrp: 899,
    discount: "61% OFF",
    rating: "4.4",
    ratingCount: "1100",
    images: ["product_images/kids_item6.png"],
    colors: ["product_images/kids_item6.png"],
    category: "kids",
    description: "Stylish kids' denim jeans",
  },
  {
    id: 31,
    title: "Kids' Shirt",
    brand: "FORMAL KIDS",
    price: 299,
    mrp: 799,
    discount: "63% OFF",
    rating: "4.2",
    ratingCount: "700",
    images: ["product_images/kids_item7.png"],
    colors: ["product_images/kids_item7.png"],
    category: "kids",
    description: "Formal shirt for kids",
  },
  {
    id: 32,
    title: "Kids' Pajama Set",
    brand: "SLEEP WEAR",
    price: 249,
    mrp: 699,
    discount: "64% OFF",
    rating: "4.5",
    ratingCount: "1300",
    images: ["product_images/kids_item8.png"],
    colors: ["product_images/kids_item8.png"],
    category: "kids",
    description: "Comfortable kids' pajama set",
  },
  {
    id: 33,
    title: "Kids' Sweater",
    brand: "WINTER WEAR",
    price: 399,
    mrp: 999,
    discount: "60% OFF",
    rating: "4.3",
    ratingCount: "800",
    images: ["product_images/kids_item9.png"],
    colors: ["product_images/kids_item9.png"],
    category: "kids",
    description: "Warm kids' sweater",
  },
  {
    id: 34,
    title: "Kids' Jacket",
    brand: "OUTER WEAR",
    price: 599,
    mrp: 1499,
    discount: "60% OFF",
    rating: "4.4",
    ratingCount: "900",
    images: ["product_images/kids_item10.png"],
    colors: ["product_images/kids_item10.png"],
    category: "kids",
    description: "Cozy kids' jacket for cold weather",
  },
];

const allProducts = [...mensProducts, ...womensProducts, ...kidsProducts];

const seedDatabase = async () => {
  try {
    await connectDB();

    // Clear existing products
    await Product.deleteMany({});

    // Insert new products
    const result = await Product.insertMany(allProducts);
    console.log(`✓ Database seeded with ${result.length} products`);
    console.log(`  - Men's products: ${mensProducts.length}`);
    console.log(`  - Women's products: ${womensProducts.length}`);
    console.log(`  - Kids' products: ${kidsProducts.length}`);

    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error.message);
    process.exit(1);
  }
};

seedDatabase();
